python -m eel game2text.py web ^
--windowed ^
--icon "public/icon.ico" ^
--hidden-import encodings ^
--hidden-import sudachidict_small ^
--hidden-import sudachipy.lattice ^
--hidden-import sudachipy.morphemelist ^
--add-data "logs;logs/" ^
--add-data "profiles;profiles/" ^
--add-data "gamescripts;gamescripts/" ^
--add-data "resources/sudachidict_small;sudachidict_small/" ^
--add-data "resources/sudachipy/resources;sudachipy/resources/" ^
--add-data "anki;anki/" ^
--add-data "resources/bin/win;resources/bin/win/" ^
--add-data "resources/dictionaries;resources/dictionaries/" ^
--add-data "config.ini;."